"""add drugs and compatibility models

Revision ID: 114c6b58e00a
Revises: 61c10be41e68
Create Date: 2025-09-22 02:28:24.212153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114c6b58e00a'
down_revision = '61c10be41e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generic_name', sa.String(length=128), nullable=False),
    sa.Column('brand_name', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generic_name')
    )
    op.create_table('compatibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('co_drug_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['co_drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compatibility')
    op.drop_table('drugs')
    # ### end Alembic commands ###
